<a href="https://colab.research.google.com/github/MSuhochev/Home_works_intro_to_Python/blob/Seminar_10/Task_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import pandas as pd

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
df = pd.DataFrame({'whoAmI':lst})
df.head(10)

  whoAmI
0  robot
1  human
2  robot
3  robot
4  human
5  human
6  human
7  robot
8  human
9  robot

In [2]:
pd.get_dummies(df, columns=['whoAmI'])

    whoAmI_human  whoAmI_robot
0              0             1
1              1             0
2              0             1
3              0             1
4              1             0
5              1             0
6              1             0
7              0             1
8              1             0
9              0             1
10             1             0
11             1             0
12             1             0
13             0             1
14             0             1
15             1             0
16             0             1
17             0             1
18             0             1
19             1             0

In [8]:
one_hot_data = pd.DataFrame({'human': [1 if i == 'human' else 0 for i in lst],
                             'robot': [1 if j == 'robot' else 0 for j in lst]})

In [9]:
one_hot_data

    human  robot
0       0      1
1       1      0
2       0      1
3       0      1
4       1      0
5       1      0
6       1      0
7       0      1
8       1      0
9       0      1
10      1      0
11      1      0
12      1      0
13      0      1
14      0      1
15      1      0
16      0      1
17      0      1
18      0      1
19      1      0